## Authors note: add "[ci skip]" or "[skip ci]" in commit message to
##  disable building for the next push.
## Required for apt-get commands within '.travis-ci/before_install_depends.sh'
##  & cp commands within '.travis-ci/install.sh' only, everything else should
##  be runing as "${USER}" for build processes.
sudo: required
## Settings for git
git:
 depth: 3
 branch: master
## Operating systems to test on
os:
 - linux
## Settings for language that travis-ci.org will test with
language:
 - bash
## easy-rsa installation as addon causes errors with other portions of build
#addons:
# apt:
#  sources:
#   - lucid
#  packages:
#   - easy-rsa
## Matrix of steps to preform for tests
matrix:
 include:
 - bash
## Custom setup prior to testing project, install dependencies & configure
##  - Run installation of VPS dependancies, minus easy-rsa, because Travis-CI
##  builds needed a bit of manual assistance.
before_install:
 - chmod +x .travis-ci/before_install.sh
 - .travis-ci/before_install.sh
## Steps for successful installing additional dependencies
##  - Run installation of easy-rsa from deb file provided by Debian mirror
install:
 - chmod +x .travis-ci/install_easy_rsa.sh
 - .travis-ci/install_easy_rsa.sh
## Steps to complete prior to running further tests.
#before_script:
# - chmod +x
# -
## Run tests that report 'Passing' or 'Failing' build states
##  - Run configuration steps for new OpenVPN server
##  - Run configuration steps for new clients of OpenVPN server
script:
 - chmod +x .travis-ci/script_configure_server_only.sh
 - .travis-ci/script_configure_server_only.sh
 - chmod +x .travis-ci/script_configure_clients_only.sh
 - .travis-ci/script_configure_clients_only.sh
## Setps to complete after success or falure
##  - Run tests of if custom iptables script for server are properly assigning
##  values and properly escaping others.
after_success:
 - chmod u+x .travis-ci/script_configure_iptables_only.sh
 - .travis-ci/script_configure_iptables_only.sh
#after_failure:
## Steps to run for deployment of build if any
#before_deploy:
#deploy:
#after_deploy:
## Steps to run when script and deployment is finished; cleanup?
#after_script:
## Note above tricks for chmoding the scripts prior to execution where found
##  at: http://stackoverflow.com/a/33820642/2632107
